name: CI

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "tests/**"
      - "data/**"
      - "requirements.txt"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "data/**"
      - "requirements.txt"
      - ".github/workflows/**"

jobs:
 lint-and-format:
   runs-on: ubuntu-latest
   steps:
     - name: Check out repository
       uses: actions/checkout@v4


     - name: Set up Python
       uses: actions/setup-python@v5
       with:
         python-version: "3.11"


     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
         pip install ruff


     - name: Run Ruff auto-fix
       run: |
         ruff check . --fix
         ruff format .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests with pytest
        run: pytest -v

  build-and-push:
    runs-on: ubuntu-latest
    needs: [test, lint-and-format]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # <-- matches your repo secret
          password: ${{ secrets.DOCKER_PASSWORD }}   # <-- matches your repo secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sentiment-analysis-app:latest
