name: CI

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "tests/**"
      - "data/**"
      - "requirements.txt"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "data/**"
      - "requirements.txt"
      - ".github/workflows/**"

jobs:
 run-formatter:
   runs-on: ubuntu-latest
   timeout-minutes: 10


   steps:
     - name: Check out repository
       uses: actions/checkout@v4


     - name: Set up Python
       uses: actions/setup-python@v5
       with:
         python-version: "3.11"


     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
        
     - name: Run the formatter script
       run: |
         python src/formatter.py --input data/sentiments.csv --output data/clean_sentiments.csv
     
     - name: Run the predictor script
       run: |
         python src/predict.py "I absolutely loved it!" "It was terrible!"



  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests with pytest
        run: pytest -v

  build-and-push:
    runs-on: ubuntu-latest
    needs: [test, run-formatter]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sentiment-analysis-app:latest

